%% Description: TODO: Add description to role_op_copy_component
-module(role_op_copy_component).
-export([
	handle_event/4,
	export_for_copy/0,
	load_by_copy/1
]).

-include("base_component_shared.hrl").
-include("data_struct.hrl").


handle_event(Event, EventContent, StateName, StateData) ->
	unhandle.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%local:for change map
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%	
export_for_copy()->
	AccountInfo = {get(account_id),get(is_adult),get(client_ip),get(login_time),get(pf),get(is_yellow_vip),get(is_yellow_year_vip),get(yellow_vip_level),get(openid),get(openkey),get(pfkey)}, 
	{
	get(current_buffer),
	get(current_attribute),
	get(base_attr),
	get(other_attr),
	get(murderer),
	get(loot_index),
	% continuous_logging_op:export_for_copy(),
	apply_component(continuous_logging_op,export_for_copy,[]),
	% invite_friend_op:export_for_copy(),
	apply_component(invite_friend_op,export_for_copy,[]),
	% role_game_rank:export_for_copy(),
	apply_component(role_game_rank,export_for_copy,[]),
	% items_op:export_for_copy(),
	apply_component(items_op,export_for_copy,[]),
	% group_op:export_for_copy(),
	apply_component(group_op,export_for_copy,[]),
	% loop_instance_op:export_for_copy(),
	apply_component(loop_instance_op,export_for_copy,[]),
	% package_op:export_for_copy(),
	apply_component(package_op,export_for_copy,[]),
	% chat_op:export_for_copy(),
	apply_component(chat_op,export_for_copy,[]),
	% quest_op:export_for_copy(),
	apply_component(quest_op,export_for_copy,[]),
	% buffer_op:export_for_copy(),
	apply_component(buffer_op,export_for_copy,[]),
	% guild_op:export_for_copy(),
	apply_component(guild_op,export_for_copy,[]),
	% skill_op:export_for_copy(),
	apply_component(skill_op,export_for_copy,[]),
	% friend_op:export_for_copy(),
	apply_component(friend_op,export_for_copy,[]),
	% achieve_op:export_for_copy(),
	apply_component(achieve_op,export_for_copy,[]),
	instance_op:export_for_copy(),
	% apply_component(instance_op,export_for_copy,[]),
	% instance_quality_op:export_for_copy(),
	apply_component(instance_quality_op,export_for_copy,[]),
	% block_training_op:export_for_copy(),
	apply_component(block_training_op,export_for_copy,[]),
	% role_chess_spirits:export_for_copy(),
	apply_component(role_chess_spirits,export_for_copy,[]),
	% activity_value_op:export_for_copy(),
	apply_component(activity_value_op,export_for_copy,[]),
	% first_charge_gift_op:export_for_copy(),
	apply_component(first_charge_gift_op,export_for_copy,[]),
	% treasure_storage_op:export_for_copy(),
	apply_component(treasure_storage_op,export_for_copy,[]),
	% role_mainline:export_for_copy(),
	apply_component(role_mainline,export_for_copy,[]),
	% guildbattle_op:export_for_copy(),
	apply_component(guildbattle_op,export_for_copy,[]),
	% country_op:export_for_copy(),
	apply_component(country_op,export_for_copy,[]),
	% spiritspower_op:export_for_copy(),
	apply_component(spiritspower_op,export_for_copy,[]),
	AccountInfo,
	% hp_package_gift:export_for_copy(),
	apply_component(spiritspower_op,export_for_copy,[]),
	% mp_package_gift:export_for_copy(),
	apply_component(spiritspower_op,export_for_copy,[]),
	get(init_buffer_tmp),
	% battle_ground_op:export_for_copy(),
	apply_component(battle_ground_op,export_for_copy,[]),
	% loop_tower_op:export_for_copy(),
	apply_component(loop_tower_op,export_for_copy,[]),
	% everquest_op:export_for_copy(),
	apply_component(everquest_op,export_for_copy,[]),
	% vip_op:export_for_copy(),
	apply_component(vip_op,export_for_copy,[]),
	% series_kill:export_for_copy(),
	apply_component(series_kill,export_for_copy,[]),
	% pet_op:export_for_copy(),
	apply_component(pet_op,export_for_copy,[]),
	% role_soulpower:export_for_copy(),
	apply_component(role_soulpower,export_for_copy,[]),
	% mall_op:export_for_copy(),
	apply_component(mall_op,export_for_copy,[]),
	% timelimit_gift_op:export_for_copy(),
	apply_component(timelimit_gift_op,export_for_copy,[]),
	% role_private_option:export_for_copy(),
	apply_component(role_private_option,export_for_copy,[]),
	% answer_op:export_for_copy(),
	apply_component(answer_op,export_for_copy,[]),
	% congratulations_op:export_for_copy(),
	apply_component(congratulations_op,export_for_copy,[]),
	% auction_op:export_for_copy(),
	apply_component(auction_op,export_for_copy,[]),
	% fatigue:export_for_copy(),
	apply_component(fatigue,export_for_copy,[]),
	% venation_op:export_for_copy(),
	apply_component(venation_op,export_for_copy,[]),
	% role_dragon_fight:export_for_copy(),
	apply_component(role_dragon_fight,export_for_copy,[]),
	% role_global_op:export_for_copy(),
	apply_component(role_global_op,export_for_copy,[]),
	% role_server_travel:export_for_copy(),
	apply_component(role_server_travel,export_for_copy,[]),
	% gm_role_privilege_op:export_for_copy(),
	apply_component(gm_role_privilege_op,export_for_copy,[]),
	% offline_exp_op:export_for_copy(),
	apply_component(offline_exp_op,export_for_copy,[]),
	% goals_op:export_for_copy(),
	apply_component(goals_op,export_for_copy,[]),
	% role_treasure_transport:export_for_copy(),
	apply_component(role_treasure_transport,export_for_copy,[]),
	% gold_exchange:export_for_copy(),
	apply_component(gold_exchange,export_for_copy,[]),
	% designation_op:export_for_copy(),
	apply_component(designation_op,export_for_copy,[]),
	% consume_return:export_for_copy(),
	apply_component(consume_return,export_for_copy,[]),
	% spa_op:export_for_copy(),
	apply_component(spa_op,export_for_copy,[]),
	% pet_explore_op:export_for_copy(),
	apply_component(pet_explore_op,export_for_copy,[]),
	% open_service_activities:export_for_copy(),
	apply_component(open_service_activities,export_for_copy,[]),
	% explore_storage_op:export_for_copy(),
	apply_component(explore_storage_op,export_for_copy,[]),
	% pvp_op:export_for_copy()
	apply_component(pvp_op,export_for_copy,[])
	}.

load_by_copy(CopyInfo)->
	{CurrentBuff,CurrentAttr,BaseAttr,OtherAttr,
	Murderer,Loot_index
	,Continuous_Info
	,Invite_friend_Info
	,JudgeInfo,ItemsInfo,GroupInfos,
	LoopInstanceInfo,
	PackageInfo,ChatInfo,QuestInfo,BufferInfo,GuildInfo,SkillInfo,FriendInfo,AchieveInfo,InstanceInfo,InstanceQualityInfo,TrainInfo,ChessInfo,
	ActivityValueInfo,
	FirstChargeGiftInfo,
	TreasureStorageInfo,
	MainLineInfo,
	GuildBattleInfo,
	CountryInfo,
	SpiritsPowerInfo,
	AccountInfo,HpPackage,MpPackage,InitBuffInfo,BattleGround,RoleLoopTower,EverQuestInfo,RoleVipInfo,SeriesKillInfo,PetsInfo,SoulPowerInfo,LatestBuyLog,TimeLimitGiftInfo,PriVateInfo,RoleAnswerInfo,
	RoleCongratuLog,AuctionInfo,FatigueInfo,VenationInfo,DragonFightInfo,GlobalInfo,ServertravelInfo,RolePrivilege,OfflineExpLog,GoalsInfo,TransportInfo,GoldConsumeInfo,DesignationInfo,ConsumeReturnInfo,
	SpaInfo,PetExploreInfo,OpenService,ExploreStorageInfo,PvpInfo} = CopyInfo,
	%%当前buff
 	{Account,IsAdult,Ip,LogInTime,Pf,Is_yellow_vip,Is_yellow_year_vip,Yellow_vip_level,OpenId,OpenKey,PfKey} = AccountInfo ,
	put(client_ip,Ip),
	put(account_id,Account),
	put(is_adult,IsAdult),
	put(login_time,LogInTime), 
	put(pf,Pf),
	put(is_yellow_vip, Is_yellow_vip),
	put(is_yellow_year_vip, Is_yellow_year_vip),
	put(yellow_vip_level, Yellow_vip_level),
	put(openid, OpenId),
	put(openkey, OpenKey),
	put(pfkey, PfKey),
	put(base_attr,BaseAttr),
	put(other_attr,OtherAttr),
	put(current_buffer, CurrentBuff),
	put(current_attribute,CurrentAttr),
	put(init_buffer_tmp,InitBuffInfo),
	put(murderer,Murderer),
	put(loot_index,Loot_index),
	% trade_role:init(),
	apply_component(trade_role,init,[]),
	% spiritspower_op:load_by_copy(SpiritsPowerInfo),
	apply_component(spiritspower_op,load_by_copy,[SpiritsPowerInfo]),
	% role_chess_spirits:load_by_copy(ChessInfo),
	apply_component(role_chess_spirits,load_by_copy,[ChessInfo]),
	% role_global_op:load_by_copy(GlobalInfo),
	apply_component(role_global_op,load_by_copy,[GlobalInfo]),
	% role_server_travel:load_by_copy(ServertravelInfo),
	apply_component(role_server_travel,load_by_copy,[ServertravelInfo]),
	% role_private_option:load_by_copy(PriVateInfo),
	apply_component(role_private_option,load_by_copy,[PriVateInfo]),
	% items_op:load_by_copy(ItemsInfo),
	apply_component(items_op,load_by_copy,[ItemsInfo]),
	% group_op:load_by_copy(GroupInfos),
	apply_component(group_op,load_by_copy,[GroupInfos]),
	% loop_instance_op:load_by_copy(LoopInstanceInfo),
	apply_component(loop_instance_op,load_by_copy,[LoopInstanceInfo]),
	% package_op:load_by_copy(PackageInfo),
	apply_component(package_op,load_by_copy,[PackageInfo]),
	% quest_op:load_by_copy(QuestInfo),
	apply_component(quest_op,load_by_copy,[QuestInfo]),
	% everquest_op:load_by_copy(EverQuestInfo),
	apply_component(everquest_op,load_by_copy,[EverQuestInfo]),
	% battle_ground_op:load_by_copy(BattleGround),
	apply_component(battle_ground_op,load_by_copy,[BattleGround]),
	% role_dragon_fight:load_by_copy(DragonFightInfo),
	apply_component(role_dragon_fight,load_by_copy,[DragonFightInfo]),
	% %%初始化chat
	% chat_op:load_by_copy(ChatInfo),
	apply_component(chat_op,load_by_copy,[ChatInfo]),
	% %%重新载入buffer
	% buffer_op:init(),
	apply_component(buffer_op,init,[]),
	% %%公会
	% guild_op:load_by_copy(GuildInfo),
	apply_component(guild_op,load_by_copy,[GuildInfo]),
	% country_op:load_by_copy(CountryInfo),
	apply_component(country_op,load_by_copy,[CountryInfo]),
	% guildbattle_op:load_by_copy(GuildBattleInfo),
	apply_component(guildbattle_op,load_by_copy,[GuildBattleInfo]),
	% skill_op:load_by_copy(SkillInfo),
	apply_component(skill_op,load_by_copy,[SkillInfo]),
	% block_training_op:load_by_copy(TrainInfo),
	apply_component(block_training_op,load_by_copy,[TrainInfo]),
	instance_op:load_by_copy(InstanceInfo),
	% apply_component(instance_op,load_by_copy,[InstanceInfo]),
	% instance_quality_op:load_by_copy(InstanceQualityInfo),
	apply_component(instance_quality_op,load_by_copy,[InstanceQualityInfo]),
	% friend_op:load_by_copy(FriendInfo),
	apply_component(friend_op,load_by_copy,[FriendInfo]),
	% achieve_op:load_by_copy(AchieveInfo),
	apply_component(achieve_op,load_by_copy,[AchieveInfo]),
	% goals_op:load_by_copy(GoalsInfo),
	apply_component(goals_op,load_by_copy,[GoalsInfo]),
	% loop_tower_op:load_by_copy(RoleLoopTower),
	apply_component(loop_tower_op,load_by_copy,[RoleLoopTower]),
	% vip_op:load_by_copy(RoleVipInfo),
	apply_component(vip_op,load_by_copy,[RoleVipInfo]),
	% gm_role_privilege_op:load_by_copy(RolePrivilege),
	apply_component(gm_role_privilege_op,load_by_copy,[RolePrivilege]),
	% answer_op:load_by_copy(RoleAnswerInfo),
	apply_component(answer_op,load_by_copy,[RoleAnswerInfo]),
	% spa_op:load_by_copy(SpaInfo),
	apply_component(spa_op,load_by_copy,[SpaInfo]),
	% congratulations_op:load_by_copy(RoleCongratuLog),
	apply_component(congratulations_op,load_by_copy,[RoleCongratuLog]),
	% offline_exp_op:load_by_copy(OfflineExpLog),
	apply_component(offline_exp_op,load_by_copy,[OfflineExpLog]),
	% series_kill:load_by_copy(SeriesKillInfo),
	apply_component(series_kill,load_by_copy,[SeriesKillInfo]),
	% pet_op:load_by_copy(PetsInfo), 
	apply_component(pet_op,load_by_copy,[PetsInfo]),
	% role_soulpower:load_by_copy(SoulPowerInfo),
	apply_component(role_soulpower,load_by_copy,[SoulPowerInfo]),
	% auction_op:load_by_copy(AuctionInfo),
	apply_component(auction_op,load_by_copy,[AuctionInfo]),
	% fatigue:load_by_copy(FatigueInfo),
	apply_component(fatigue,load_by_copy,[FatigueInfo]),
	% mall_op:load_by_copy(LatestBuyLog),
	apply_component(mall_op,load_by_copy,[LatestBuyLog]),
	% role_mainline:load_by_copy(MainLineInfo),
	apply_component(role_mainline,load_by_copy,[MainLineInfo]),
	% continuous_logging_op:load_by_copy(Continuous_Info),
	apply_component(continuous_logging_op,load_by_copy,[Continuous_Info]),
	% invite_friend_op:load_by_copy(Invite_friend_Info),
	apply_component(invite_friend_op,load_by_copy,[Invite_friend_Info]),
	% role_game_rank:load_by_copy(JudgeInfo),
	apply_component(role_game_rank,load_by_copy,[JudgeInfo]),
	% pvp_op:load_by_copy(PvpInfo),
	apply_component(pvp_op,load_by_copy,[PvpInfo]),
	% activity_value_op:load_by_copy(ActivityValueInfo),
	apply_component(activity_value_op,load_by_copy,[ActivityValueInfo]),
	% first_charge_gift_op:load_by_copy(FirstChargeGiftInfo),
	apply_component(first_charge_gift_op,load_by_copy,[FirstChargeGiftInfo]),
	% treasure_storage_op:load_by_copy(TreasureStorageInfo),
	apply_component(treasure_storage_op,load_by_copy,[TreasureStorageInfo]),
	% AllBufferInfo = buffer_op:get_from_copy(BufferInfo),
	AllBufferInfo = apply_component(buffer_op,get_from_copy,[BufferInfo]),
	% hp_package_gift:load_by_copy(HpPackage),
	apply_component(hp_package_gift,load_by_copy,[HpPackage]),
	% mp_package_gift:load_by_copy(MpPackage),
	apply_component(mp_package_gift,load_by_copy,[MpPackage]),
	% timelimit_gift_op:load_by_copy(TimeLimitGiftInfo),
	apply_component(timelimit_gift_op,load_by_copy,[TimeLimitGiftInfo]),
	% venation_op:load_by_copy(VenationInfo),
	apply_component(venation_op,load_by_copy,[VenationInfo]),
	% gold_exchange:load_by_copy(GoldConsumeInfo),
	apply_component(gold_exchange,load_by_copy,[GoldConsumeInfo]),
	% role_treasure_transport:load_by_copy(TransportInfo),
	apply_component(role_treasure_transport,load_by_copy,[TransportInfo]),
	% designation_op:load_by_copy(DesignationInfo),
	apply_component(designation_op,load_by_copy,[DesignationInfo]),
	% consume_return:load_by_copy(ConsumeReturnInfo),
	apply_component(consume_return,load_by_copy,[ConsumeReturnInfo]),
	% pet_explore_op:load_by_copy(PetExploreInfo),
	apply_component(pet_explore_op,load_by_copy,[PetExploreInfo]),
	% open_service_activities:load_by_copy(OpenService),
	apply_component(open_service_activities,load_by_copy,[OpenService]),
	% explore_storage_op:load_by_copy(ExploreStorageInfo),
	apply_component(explore_storage_op,load_by_copy,[ExploreStorageInfo]),
	init_buffers_by_node(AllBufferInfo).


init_buffers_by_node(NewBuffers_with_Time)->
	%% 触发由Buffer导致的事件
 	lists:foreach(fun({BufferID, BufferLevel,StartTime,CasterInfo}) ->
				      buffer_op:generate_interval(BufferID, BufferLevel, 0,StartTime,CasterInfo)
			  end, NewBuffers_with_Time).